# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EpiNews' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EpiNews
  pod 'AppCenter/Crashes', '~> 1.5.0'
  pod 'AppCenterReactNativeShared', '~> 1.4.0'
  pod 'AppCenter/Analytics', '~> 1.5.0'

  

  platform :ios, '9.0'
  target 'EpiNewsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'EpiNews-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for EpiNews-tvOS

  target 'EpiNews-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
